# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Test

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:

  build:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 15
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod

    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v ./... -coverprofile=coverage.out

    - name: check coverage
      uses: k1LoW/octocov-action@a167dc0dee441b7ffc45e1b862ab55ec0d87f278 # v1.5.2
